plugins {
    id 'com.android.application'
}

android {
    namespace 'ly.moi.forceerp'
    compileSdk 35

    defaultConfig {
        applicationId 'ly.moi.forceerp'
        minSdk 26
        targetSdk 35
        versionCode 71
        versionName "7.1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}